apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: jenkins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins-server
  type: LoadBalancer
